### ISSUE TITLE
Not using the batch ran embeddings

### ISSUE THREAD

**Issue by divakaivan** [mrdbourke/simple-local-rag#2]
I am following through the video, and just want to check.
When we create the embeddings, first we do:
```python
embedding_model.to('cuda')

for item in tqdm(pages_and_chunks_over_min_token_len):
    item["embedding"] = embedding_model.encode(item["sentence_chunk"])
```
which finishes. After, you show us the fast version which is
```python
# embed all texts in batches (fastest way)
text_chunk_embeddings = embedding_model.encode(text_chunks, batch_size=32, convert_to_tensor=True)
text_chunk_embeddings
```

but in the code afterwards, we do not use these text_chunk_embeddings, we use the pages_and_chunks_over_min_token_len which were modified in the first piece of code above.
```python
# Save embeddings to file
text_chunks_and_embeddings_df = pd.DataFrame(pages_and_chunks_over_min_token_len)
embeddings_df_save_path = "text_chunks_and_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)
```
I noticed that because I ran the former, and stopped it after a few seconds because it was very slow, so I just ran the batched version which was moderately quick. And afterwards before step 2 - starting the RAG, I noticed that almost all of my embedding values in my df are `nan`s. Thats because I stopped the first code after a few secs - and in that time it only embedded a small portion of the rows. 

just leaving this for someone else who might encounter this issue. :)

**Comment by DanielTobi0** [comment]
same issue. How did you resolve it?
