### ISSUE TITLE
import error for `fitz`

### ISSUE THREAD

**Issue by jayabrata97** [mrdbourke/simple-local-rag#7]
Hi, I was trying to re implement the code for learning. I am getting import error for `import fitz`. It is giving error `ModuleNotFoundError: No module named 'fitz'`. The similar error is coming if I replace it with `import pymupdf`. Anyone has any clue for this?

**Comment by M-Ali-ML** [comment]
You will have to `!pip install PyMuPDF`, as mentioned in the commented line before the import in the notebook.
What that do is download the required library as it is not available in the google colab default libraries

**Comment by jayabrata97** [comment]
Hi @MightyStud, thanks for the reply. I have solved the issue. I am not using the notebook. I am directly using the conda env installation. There were some issues related to that environment. That was giving the error. Here are some clues: `https://stackoverflow.com/questions/56658553/why-do-i-get-a-modulenotfounderror-in-vs-code-despite-the-fact-that-i-already` and `https://stackoverflow.com/questions/72322120/vscode-import-x-could-not-be-resolved-even-though-listed-under-helpmodules`.
